spring:
  data:
    mongodb:
      username: admin
      password: admin
      host: localhost   # <-- container name from docker-compose
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
